[build]
  publish = "_site"
  command = "DEBUG=* eleventy"

[[redirects]]
  from = "/feed/feed.xml"
  to = "/feed.xml"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    cache-control = '''
    public
    max-age=1800'''